# Generated by Django 5.0.2 on 2024-02-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_contacts_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="question",
            field=models.TextField(null=True),
        ),
    ]
