# Generated by Django 5.0.2 on 2024-02-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_alter_categories_options_alter_categories_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("id",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
