# Generated by Django 5.0.2 on 2024-02-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_product_height_product_length_product_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                decimal_places=0, default=0.0, max_digits=7, verbose_name="Высота"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                decimal_places=0, default=0.0, max_digits=7, verbose_name="Ширина"
            ),
        ),
    ]
