# Generated by Django 5.0.2 on 2024-02-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0006_alter_product_height_alter_product_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                decimal_places=0, default=0.0, max_digits=7, verbose_name="Длина"
            ),
        ),
    ]
